CREATE TABLE IF NOT EXISTS students (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  group_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS attendance (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  student_id INTEGER NOT NULL,
  class_type TEXT NOT NULL,
  date TEXT NOT NULL,
  paid INTEGER NOT NULL,
  FOREIGN KEY(student_id) REFERENCES students(id)
);